export {default as Navbar } from "./Navbar"
export {default as Footer } from "./Footer"
export {default as Hero } from "./Hero"
export {default as MiniGame } from "./MiniGame"
export {default as ContactForm } from "./ContactForm"
export {default as PageLoader } from "./PageLoader"
